name: tomorecon-meta
channels:
  - defaults
  - nvidia
  - conda-forge
  - pytorch
dependencies:
#  - torchvision
  - python=3.9
#  - pytorch
#  - pytorch-cuda=11.3
#  - cudatoolkit=11.3
  - numpy
  - matplotlib
  - tqdm
  - pip
  - pip:
    - wandb
    - hydra-core
    - h5py
    - scikit-image
    - hydra-optuna-sweeper
    - black
